
a=int(input("3"))
if a==3:
    list=["Amonyak(1)","Karbonat(2)","Bakır(II)sülfat(3)", ]
    print(list)
    g=int(input("Bileşik seçiniz:"))
    if g==1 :
        print("           Amonyak(NH3)")
        print(" ")
        print("   Amonyak, formülü NH3 olan; azot atomu ve hidrojen atomundan oluşan renksiz, keskin ve hoş olmayan kokuya sahip bir gaz bileşiğidir. OH- iyonu içermediği halde suda zayıf baz özelliği gösterir. Bir amonyak molekülü, bir azot ve üç hidrojen atomundan oluşur.")
        print(" ")
        print("           Günlük Hayatta Kullanımı")
        print(" ")
        print("   Amonyak, gübre, ilaç, boya, parfüm gibi maddelerin sentezlenmesinde ilk aşamada kullanılmaktadır. Amonyak canlılar için zehirli bir maddedir, kullanılırken dikkat edilmesi gerekir. Piyasada amonyak adı altında satılan maddeler amonyağın sulu çözeltisi olan amonyum hidroksittir.")
    if g==2 :
        print("           Karbonat(CO3)")
        print(" ")
        print("   Karbonat, kimyada karbonik asitin bir tuzudur. Karbonat iyonu CO32- varlığında nitelendirilir. Aynı zamanda ismi karbonik asitin esteri manasına da gelebilir.Jeoloji ve mineralojide karbonat terimi hem karbonat minerallerine, hem de karbonat taşlarına tekabül eder ve her ikisi de CO32- şeklinde ifade edilir.")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("   Karbonat, hamur işi tariflerinin vazgeçilmezi olarak bilinir,Karbonat aynı zamanda iyi bir diş temizleyicidir. Dişlerde çay, kahve ve sigaradan dolayı oluşan sarı lekelerin temizlenmesinde yardımcı olur.Karbonat, içinde barındırdığı anti bakteriyel özelliği sayesinde yer yüzeylerinin temizliği ve hijyeninde kullanılabilir. Etkin bir mikrop öldürücüdür aynı zamanda böcek ve zararlı haşaratı da kokusu sayesinde bulunduğunuz mekanlardan uzak tutacaktır.tekstil ürünlerinizde oluşacak lekelerin temizliği için karbonat tercih edebilirsiniz.")
    if g==3:
        print("           Bakır(II)sülfat(CuSO4)")
        print(" ")
        print("   Küprik sülfat ya da bakır sülfat olarak da denilen Bakır(II) sülfat, kimyasal formülü CuSO4 olan bir kimyasal bileşiktir. Bu tuzun hidrasyon derecelerine bağlı olarak bir dizi farklı bileşikleri mevcuttur. Susuz formu soluk yeşil ya da grimsi beyaz bir toz olmasına karşın en çok bilinen pentahidrat (CuSO4•5H2O) formu, parlak mavi renktedir. Çok az miktardaki CuSO4•5H2O çevreye çok zehirlidir, gözleri ve cildi tahriş eder ve yutulduğunda zararlı da olabilir. Oktahedral moleküler geometriye ve paramanyetik özelliğe sahip olan bakır(II) sülfat ekzotermik olarak suda çözünürek [Cu(H2O)6]2+ kompleksini oluşturur. Bakır(II) sülfat mavi vitriyol, göztaşı ve göktaşı olarak da bilinmektedir.")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("    Bakır(II) sülfat bağlardaki ve meyve bahçelerindeki mantar hastalıkları ile mücadele amacıyla zirai ilaçların kullanılmasında etkin maddedir. Su borularının işgalci sucul bitkilerin köklerine karşı herbisit olarak bakır sülfat kullanılır. Yosun giderici şeklinde yüzme havuzlarında temizleyici olarak kullanılır. Seyreltik şeklindeki sülfat çözeltisi akvaryumda yaşayan balıklar parazit enfeksiyonları tedavisinde kullanılır ve akvaryumlarda bulunan salyangozları öldürmek için de bakır sülfat çözeltisi kullanılabilir.")
    if g==4:
        print("           Sülfürik asit(H2SO4)")
        print(" ")
        print("   Sülfürik(VI) asit ya da halk arasında bilinen ismi ile zaç yağı, H2SO4, güçlü bir mineral asididir. Olası kaşifi 8. yüzyıl simyacısı Cabir bin Hayyan tarafından yenime uğratıcı, renksiz ve yoğunluğu yüksek sıvı olarak tanımlanmıştır. Suda her konsantrasyonda çözünebilir. Büyük ölçüde korozif oluşu, güçlü asidik yapısından ve dehidrasyon özelliğinden kaynaklanmaktadır.")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("    Sülfürik asit çeşitli derişimleri durumunda gübre, pigment, boyar madde, patlayıcı madde, ilaçlama, inorganik tuz ve petrol arıtım ile metalurji işlemlerinde kullanılmaktadır. Bunların yanı sıra çeşitli pillerin yapımlarında da sülfürik asitten yararlanıldığını görebilmek mümkündür. Bu asidin halk arasında akü asidi olarak bilindiğini söyleyebiliriz.")
    if g==5:
        print("           Sodyum bikarbonat(NaHCO3)")
        print(" ")
        print("   Sodyum bikarbonat ya da soda kimyasal formulü NaHCO3 olan bir kimyasal bileşiktir. Kabartma tozu olarak da bilinir. Sodyum tuzlarından birisidir. Antiasit özelliği vardır. Kabartma tozu olarak da kullanılır. Suda çözünür. Beyaz katı kristal tozdur. Sodyum karbonat'ı andıran hafif alkali tadı vardır. Salin solüsyonu bileşiminde de kullanılır.")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("   Sodyum bikarbonat, halk arasında sıklıkla hamur kabartma tozu olarak bilindiği için, bu şekilde kullanımı yaygındır. Ancak bunun yanı sıra yanmış tepsilerin ve tencerelerin rahat bir şekilde temizlenebilmesi için iyi bir çözümdür ayrıca demliklerin içerisindeki kalıntıların, termoslardaki ve vazolardaki kalıntıların temizlenmesinde de kullanılır.Ayrıca ağız kokusu olanların da derdine çare olabilmektedir. İstenmeyen kokuları önleyen bu madde, lavabo kokularının önlenmesi, ayakkabı kokularının giderilmesi, buzdolabı kokularının giderilmesi için de kullanılabilir.Böcek sokmaları sonrasında, böcek ısırığının olduğu yere sodyum bikarbonatlı su ile uygulama yapıldığında ısırılan bölgedeki kaşıntıyı engellemektedir.Güneş yanıklarında sodyum bikarbonatlı su yanan bölgeye anında uygulanırsa, yanık bölgedeki ağrıyı hafifletmektedir.")
    if g==6:
        print("           Sirke ruhu(CH3COOH)")
        print(" ")
        print("  ")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("   ")
    if g==7:
        print("            Sodyum hidroksit(NaOH)")
        print(" ")
        print("   Kostik ve kostik soda olarak da bilinen sodyum hidroksit (kostik soda veya sud kostik de denir),[3][4] NaOH formülüne sahip bir inorganik bileşiktir. Sodyum katyonları Na+ ve hidroksit anyonları OH− içeren beyaz renkli katı bir iyonik bileşiktir.")
        print(" ")
        print("            Günlük Hayatta Kullanımı")
        print(" ")
        print("   En kuvvetli baz olan kostiğin kullanım alanı çok geniştir. Tekstil endüstrisinde kostik kullanılır. Sabun ve temizlik malzemeleri imalatında kullanımı vardır. Özellikle sıvı ve katı sabun yapımında.Petrol rafinelerinde kostik kullanılır. Yapay ipek yapımında kostik kullanılır. Kağıt hamuru ve kağıt üretiminde kostik kullanılır.PH yükseltilmesi gereken yerlerde kostik kullanılır. Arıtmalarda asidik ortamın nötralizasyonunda ve çöktürme amaçlı kostik kullanılır. Boya kimyasalları sektöründe kostik kullanılır.Zeytinin işlemesinde kostik kullanılır. Saf su üretiminde (İyon Değiştirici Reçinelerin Rejenerasyonunda) ve su arıtma da kostik kullanılır. Patlayıcı maddelerin üretiminde kostik kullanılır. Tarımsal kimyasaalların üretilmesinde kostik kullanılır. İlaç endüstrisinde kostik kullanılır.")
    